---
title: "Process external data not in INBOVEG or fieldmap"
date: "`r lubridate::now()`"
output: 
  html_document:
    number_sections: yes
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(git2rdata)
library(n2khab)
library(sf)
library(RODBC)
```

# Bosconstantie and msa forest habitat types

The original data is stored in [this google drive folder](https://drive.google.com/drive/folders/1WUSaPx6sLYWQ4wg-kDvl9oku17CeCuAC).

```{r}
 
data_path_gis <- file.path(fileman_up("n2khab-mhq-data"), "/raw")

bosconstantie <- st_read(dsn = file.path(data_path_gis, "bosconstantie"), layer = "Blftd", quiet = TRUE) %>%
  select(blk = BLK) %>%
  st_transform(crs = 31370)

check_bc <- bosconstantie %>%
  st_drop_geometry() %>%
  group_by(blk) %>%
  summarise(n = n()) %>%
  ungroup()

bosconstantie_91E0_sf <- read_csv2(file.path(data_path_gis, "bosconstantie/bosconstantie_91E0_sf_20241216.csv"))

msa_clusters <- read_csv2(file.path(data_path_gis, "msa/clusters_msa_v2023.csv"))

msa_type <- read_csv2(file.path(data_path_gis, "msa/msa_v2023.csv"))
  
habmap_terr <- read_habitatmap_terr()
```

## MONEOS: 91E0_sf

```{r}

data_path_processed <- file.path(fileman_up("n2khab-mhq-data"), "/processed/inboveg_mhq_terr")

path <- fileman_up("n2khab-mhq-data")

coordinates_moneos_91E0_sf <- read_vc(file = "coordinates_moneos_91E0_sf",
                                      root = data_path_processed)

plot_91E0_sf_bosconstantie <- bosconstantie_91E0_sf %>%
  select(plot_id, jaar_bos = bosconstantie) %>%
  mutate(bosconstantie = 2025 - jaar_bos + 2)

msa_type_91E0_sf <- msa_type %>%
  filter(type == "91E0_sf")

plot_91E0_sf_msa <- coordinates_moneos_91E0_sf %>%
  select(plot_id, x, y) %>%
    filter(!is.na(x)) %>%
    st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  st_join(select(habmap_terr$habitatmap_terr_polygons, polygon_id)) %>%
  st_drop_geometry() %>%
  select(plot_id, polygon_id) %>%
  left_join(msa_clusters, by = "polygon_id") %>%
  left_join(msa_type_91E0_sf, by = "cluster_id") %>%
  select(plot_id, msa_area_ha) %>%
  unique()

```

## vbi forest

```{r}
data_path_vbi <- file.path(fileman_up("n2khab-mhq-data"), "/raw/vbi")

db_meetproces <- file.path(data_path_vbi, "vbi_meetproces_v2024-08-15.accdb")

connect_db <-   odbcConnectAccess2007(db_meetproces)
coordinaten_orig <- sqlFetch(connect_db, "tblcoordinaten")
odbcClose(connect_db)

coordinates_vbi <- coordinaten_orig %>%
  select(plot_id = idplots, periode, x, y)

vbi_bosconstantie <- coordinates_vbi %>%
  st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  st_join(bosconstantie) %>%
  st_drop_geometry() %>%
  filter(!is.na(blk))

vbi_msa <- coordinates_vbi %>%
  st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  st_join(select(habmap_terr$habitatmap_terr_polygons, polygon_id)) %>%
  st_drop_geometry() %>%
  select(plot_id, periode, polygon_id) %>%
  left_join(msa_clusters, by = "polygon_id") %>%
  left_join(msa_type, by = "cluster_id") %>%
  select(plot_id, periode, type, msa_area_ha) %>%
  filter(!is.na(msa_area_ha)) %>%
  unique()

```

## mhq forest

```{r}
data_path_mhq <- file.path(fileman_up("n2khab-mhq-data"), "/processed/fieldmap_mhq")

coordinates_mhq <- read_vc("coordinates", root = data_path_mhq)

coordinates_mhq <- coordinates_mhq %>%
  select(plot_id, date_assessment, x_measured, y_measured)

#2180
data_path_mhq_duinen <- file.path(fileman_up("n2khab-mhq-data"), "/processed/inboveg_mhq_terr")

header_mhq_duinen <- read_vc("header_mhq_terr", root = data_path_mhq_duinen) %>%
  filter(str_detect(survey, "Duinen")) %>%
  filter(area == 9)

coordinates_mhq_duinen <- header_mhq_duinen %>%
  select(plot_id = user_reference, recording_givid, date_assessment = vague_date_begin, x_measured = longitude, y_measured = latitude) %>%
  mutate(date_assessment = as.Date(date_assessment)) %>%
  unique() %>%
  st_as_sf(coords = c("x_measured", "y_measured"), crs = 4326) %>%
  st_transform(crs = 31370)

mhq_bosconstantie <- coordinates_mhq %>%
  mutate(plot_id = as.character(plot_id)) %>%
  st_as_sf(coords = c("x_measured", "y_measured"), crs = 31370) %>%
  bind_rows(coordinates_mhq_duinen) %>%
  st_join(bosconstantie) %>%
  st_drop_geometry() %>%
  filter(!is.na(blk)) %>%
  unique()

mhq_msa <- coordinates_mhq %>%
  mutate(plot_id = as.character(plot_id)) %>%
  st_as_sf(coords = c("x_measured", "y_measured"), crs = 31370) %>%
  bind_rows(coordinates_mhq_duinen) %>%
  st_join(select(habmap_terr$habitatmap_terr_polygons, polygon_id)) %>%
  st_drop_geometry() %>%
  select(plot_id, recording_givid, date_assessment, polygon_id) %>%
  left_join(msa_clusters, by = "polygon_id") %>%
  left_join(msa_type, by = "cluster_id") %>%
  select(plot_id, recording_givid, date_assessment, type, msa_area_ha) %>%
  filter(!is.na(msa_area_ha)) %>%
  unique()

```


## Write result to .vc file

```{r, eval= update}

path <- str_c(fileman_up("n2khab-mhq-data"), "/processed")

if (!dir.exists(path)) {
    
  dir.create(path)  
    
}

path <- str_c(fileman_up("n2khab-mhq-data"), "/processed/extra_var_mhq")

if (!dir.exists(path)) {
    
  dir.create(path)  
    
}

write_vc(plot_91E0_sf_bosconstantie, "bosconstantie_91E0_sf", root = path, sorting = c("plot_id"), strict = FALSE)
write_vc(plot_91E0_sf_msa, "msa_91E0_sf", root = path, sorting = c("plot_id"), strict = FALSE)
write_vc(mhq_bosconstantie, "bosconstantie_mhq", root = path, sorting = c("plot_id", "date_assessment"), strict = FALSE)
write_vc(mhq_msa, "msa_mhq", root = path, sorting = c("plot_id", "date_assessment", "type"), strict = FALSE)
write_vc(vbi_bosconstantie, "bosconstantie_vbi", root = path, sorting = c("plot_id", "periode"))
write_vc(vbi_msa, "msa_vbi", root = path, sorting = c("plot_id", "periode", "type"), strict = FALSE)

```
