---
title: "Export data from inboveg database: terrestrial habitat types and aquatic habitat types measured by INBO"
date: "`r lubridate::now()`"
output: 
  html_document:
    number_sections: yes
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(odbc)
library(inbodb)
library(git2rdata)
library(n2khab)
```

# Query INBOVEG terrestrial habitat types

## Query database

```{r}
update <- TRUE
```

```{r connection and query, eval= update}
 
connection_inboveg <- connect_inbo_dbase(database_name = "D0010_00_Cydonia")

classif_mhq <- bind_rows(
    get_inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", collect = TRUE),
    get_inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", collect = TRUE),
    get_inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", collect = TRUE),
    get_inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", collect = TRUE),
    get_inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", collect = TRUE)
) %>%
    select(recording_givid = RecordingGivid, survey = Name, type_observed = Classif, classif_type = ActionGroup, classif_key = ListName, type_cover = Cover) %>%
    filter(classif_type == "N2k") %>%
    select(-classif_type)

header_mhq <- bind_rows(
    get_inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", collect = TRUE),
    get_inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", collect = TRUE),
    get_inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", collect = TRUE),
    get_inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", collect = TRUE),
    get_inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", collect = TRUE)) %>%
    select(recording_givid = RecordingGivid, survey = Name, user_reference = UserReference, area = Area, vague_date_begin = VagueDateBegin, vague_date_end = VagueDateEnd, latitude = Latitude, longitude = Longitude)

recordings_mhq <- bind_rows(
    get_inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", collect = TRUE),
    get_inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", collect = TRUE),
    get_inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", collect = TRUE),
    get_inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", collect = TRUE),
    get_inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", collect = TRUE)) %>%
    select(survey = Name, recording_givid = RecordingGivid, layer_code = LayerCode, layer_cover = CoverCode, name_original = OrignalName, name_scientific = ScientificName, phenology_code = PhenologyCode, species_cover_code = CoverageCode, species_cover = PctValue, scale = RecordingScale)

qualifiers_mhq <- bind_rows(get_inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", qualifier_type = "MQ"),
                            get_inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", qualifier_type = "MQ"),
                            get_inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", qualifier_type = "MQ"),
                            get_inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", qualifier_type = "MQ"),
                            get_inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", qualifier_type = "MQ")) %>%
    select(survey = Name, recording_givid = RecordingGivid, user_reference = UserReference, structure_var_code = Q2Code, structure_var = Q2Description, cover = Q3Description) %>%
    mutate(structure_var_code = tolower(structure_var_code),
           structure_var = tolower(structure_var),
           cover = as.numeric(cover))

```

## Write result to .vc file

```{r, eval= update}

path <- str_c(fileman_up("n2khab-mhq-data"), "/processed")

if (!dir.exists(path)) {
    
  dir.create(path)  
    
}

path <- str_c(fileman_up("n2khab-mhq-data"), "/processed/inboveg_mhq_terr")

if (!dir.exists(path)) {
    
  dir.create(path)  
    
}

write_vc(classif_mhq, "classif_mhq_terr", root = path,  sorting = c("recording_givid", "type_observed"), strict = FALSE)
write_vc(header_mhq, "header_mhq_terr", root = path,  sorting = c("recording_givid"), strict = FALSE)
write_vc(qualifiers_mhq, "structure_mhq_terr", root = path,  sorting = c("recording_givid", "structure_var"))
write_vc(recordings_mhq, "vegetation_mhq_terr", root = path,  sorting = c("recording_givid", "layer_code", "name_scientific"))
```

# Query INBOVEG aquatic habitat types

## Query database

```{r}
update <- TRUE
```

```{r connection and query aq, eval= update}
 
connection_inboveg <- connect_inbo_dbase(database_name = "D0010_00_Cydonia")
surveys <- c("HT31xx_LSVI_StilstaandeWateren", "HT31xx_Plassen", "HT3260")

classif_mhq <- get_inboveg_classification(connection = connection_inboveg, 
                                          survey_name = surveys, multiple = TRUE,
                                          collect = TRUE) %>%
    select(recording_givid = RecordingGivid, survey = Name, type_observed = Classif, 
           classif_type = ActionGroup, classif_key = ListName, type_cover = Cover) %>%
    filter(classif_type == "N2k") %>%
    select(-classif_type)

header_mhq <- get_inboveg_header(connection = connection_inboveg, 
                                 survey_name = surveys, multiple = TRUE,
                                 collect = TRUE) %>%
    select(recording_givid = RecordingGivid, survey = Name, user_reference = UserReference, 
           area = Area, vague_date_begin = VagueDateBegin, vague_date_end = VagueDateEnd, 
           latitude = Latitude, longitude = Longitude)

recordings_mhq <- get_inboveg_recording(connection = connection_inboveg, 
                                        survey_name = surveys, multiple = TRUE,
                                        collect = TRUE) %>%
    select(survey = Name, recording_givid = RecordingGivid, layer_code = LayerCode, 
           layer_cover = CoverCode, name_original = OrignalName, name_scientific = ScientificName, 
           phenology_code = PhenologyCode, species_cover_code = CoverageCode, species_cover = PctValue, 
           scale = RecordingScale)

qualifiers_m_mhq <- get_inboveg_qualifier(connection = connection_inboveg, 
                                        survey_name = surveys, multiple = TRUE,
                                        qualifier_type = "MQ") %>%
    select(survey = Name, recording_givid = RecordingGivid, user_reference = UserReference, 
           var_code = Q2Code, var = Q2Description, var_description_or_value = Q3Description, value = Elucidation) %>%
    mutate(var_code = tolower(var_code), var = tolower(var))
# oorspronkelijke objectnaam is gewijzigd om onderscheid met site en layer qualifiers te maken; hopelijk ok?
# to do: nagaan of alle kenmerken+waarde meekomen, want gerangschikt in verschillende kolommen

qualifiers_s_mhq <- get_inboveg_qualifier(connection = connection_inboveg,
                                 survey_name = surveys, multiple = TRUE, 
                                 qualifier_type = "SQ") %>% 
  mutate(var = "betrouwbaarheid") %>% 
  select(survey = Name, recording_givid = RecordingGivid, user_reference = UserReference, 
         var, value = Q1Description, remark = Elucidation)
  
qualifiers_l_mhq <- get_inboveg_layer_cover(connection = connection_inboveg, 
                                       survey_name = surveys,
                                       multiple = TRUE) %>% 
  select(survey = Name, recording_givid = RecordingGivid, user_reference = UserReference,
         var = LayerDescription, value = CoverCode, value_perc = Percentage)

dbDisconnect(connection_inboveg)
```

## Write result to .vc file

```{r, eval= update}

path <- str_c(fileman_up("n2khab-mhq-data"), "/processed")

if (!dir.exists(path)) {
    
  dir.create(path)  
    
}

path <- str_c(fileman_up("n2khab-mhq-data"), "/processed/inboveg_mhq_aq")

if (!dir.exists(path)) {
    
  dir.create(path)  
    
}

write_vc(classif_mhq, "classif_mhq_aq", root = path,  sorting = c("recording_givid", "type_observed"), strict = FALSE)
write_vc(header_mhq, "header_mhq_aq", root = path,  sorting = c("recording_givid"), strict = FALSE)
write_vc(qualifiers_m_mhq, "structure_mhq_aq", root = path,  sorting = c("recording_givid", "var")) 
# to do: check error --> owv expliciete vermelding NA in inboveg? bv Diepte van Secchibepaling bij IV2021102612312292; opl: wegfilteren bij qualifiers_m_mhq?
write_vc(qualifiers_s_mhq, "sitequal_mhq_aq", root = path,  sorting = c("recording_givid")) # to do: check error
write_vc(qualifiers_l_mhq, "layerqual_mhq_aq", root = path,  sorting = c("recording_givid", "var")) # to do: check warning
write_vc(recordings_mhq, "vegetation_mhq_aq", root = path,  sorting = c("recording_givid", "layer_code", "name_scientific"))
# to do: check warning
```